// Auth
export const LOGIN_USER_REQUEST = 'auth/LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'auth/LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'auth/LOGIN_USER_FAILURE';

export const BITCOINCASH_URL_RESULT = 'bitcoincash/BITCOINCASH_URL_RESULT';
export const SAVE_BITCOIN_CASH = 'bitcoincash/SAVE_BITCOIN_CASH';